import { LinearProgress } from "@mui/material";
import { Metadata } from "next";
import React, { Suspense } from "react";

export const metadata: Metadata = {
  title: "ERP-System | Installation",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}
const PageLayout: React.FC<LayoutProps> = ({ children }) => {
  return <Suspense fallback={<LinearProgress />}>{children}</Suspense>;
};

export default PageLayout;
